/* Shared product catalog for the Roll Now shop — loaded before products.jsx and product-detail.jsx */
window.PRODUCTS = [
  {
    id: "mb84-blackred", name: "Macroblade 84", color: "Black / Red", price: 599,
    img: "assets/products/p1.webp", accent: "var(--red-600)", badge: "Fitness", category: "Fitness Skate",
    tagline: "The all-rounder that turns commutes into training.",
    description: "The Macroblade 84 is our go-to first performance skate. A supportive molded cuff and a padded liner lock your ankle in, while the 84mm wheels keep you rolling fast and smooth over city paths and park loops. Comfortable enough for a beginner's first session, quick enough to keep up as you improve.",
    tech: [
      { title: "84mm / 84A Wheels", desc: "A balance of speed and control that suits everything from first strides to long fitness laps." },
      { title: "Extruded Aluminium Frame", desc: "Stiff and light for direct power transfer and confident stops." },
      { title: "SG9 Bearings", desc: "Smooth, durable roll that keeps momentum with less effort." },
      { title: "3-Point Closure", desc: "Laces, a 45° power strap and a cuff buckle wrap the foot for a locked-in fit." },
    ],
    target: "Beginner to intermediate skaters who want one comfortable, supportive skate for learning, fitness and easy city cruising.",
    specs: { Wheels: "84mm / 84A", Bearings: "SG9", Frame: "Extruded aluminium", Liner: "Comfort padded", Closure: "Lace + strap + buckle", Sizes: "UK 4 – 12" },
  },
  {
    id: "mb84-lime", name: "Macroblade 84", color: "Black / Lime", price: 599,
    img: "assets/products/p2.webp", accent: "var(--green-500)", badge: "Fitness", category: "Fitness Skate",
    tagline: "Same trusted ride, with a jolt of colour.",
    description: "The Macroblade 84 in black and lime brings the same supportive, fast-rolling fitness build with a brighter look. The molded cuff and padded liner deliver all-day comfort, and the 84mm setup makes it an easy, confidence-building ride for newer skaters who still want pace.",
    tech: [
      { title: "84mm / 84A Wheels", desc: "Versatile size that rolls fast yet stays easy to control." },
      { title: "Extruded Aluminium Frame", desc: "Lightweight and rigid for efficient, stable strides." },
      { title: "SG9 Bearings", desc: "Reliable, smooth roll session after session." },
      { title: "3-Point Closure", desc: "Lace, power strap and cuff buckle for a secure, custom fit." },
    ],
    target: "Newer and improving skaters after a comfortable, supportive fitness skate that stands out.",
    specs: { Wheels: "84mm / 84A", Bearings: "SG9", Frame: "Extruded aluminium", Liner: "Comfort padded", Closure: "Lace + strap + buckle", Sizes: "UK 4 – 12" },
  },
  {
    id: "mb90-blackred", name: "Macroblade 90", color: "Black / Red", price: 749,
    img: "assets/products/p3.webp", accent: "var(--red-600)", badge: "Speed", category: "Performance Skate",
    tagline: "Bigger wheels, longer glide, more speed.",
    description: "Step up to the Macroblade 90. Larger 90mm wheels and a longer frame stretch out your glide and lift your top speed, while the supportive cuff keeps everything stable at pace. Built for skaters who've found their rhythm and want to cover more ground, faster.",
    tech: [
      { title: "90mm / 84A Wheels", desc: "Larger diameter carries more speed and rolls over rough tarmac with ease." },
      { title: "Longer Aluminium Frame", desc: "Extra wheelbase adds stability and a smoother, faster glide." },
      { title: "SG9 Bearings", desc: "Free-rolling and hard-wearing for long distances." },
      { title: "3-Point Closure", desc: "Lace, power strap and buckle for a performance-grade lockdown." },
    ],
    target: "Intermediate skaters chasing more speed and distance on fitness rides and longer commutes.",
    specs: { Wheels: "90mm / 84A", Bearings: "SG9", Frame: "Extruded aluminium", Liner: "Comfort padded", Closure: "Lace + strap + buckle", Sizes: "UK 4 – 12" },
  },
  {
    id: "mb90-navy", name: "Macroblade 90 W", color: "Navy / White", price: 749,
    img: "assets/products/p4.webp", accent: "var(--blue-500)", badge: "Women's", category: "Women's Performance",
    tagline: "Speed and glide, shaped for a woman's fit.",
    description: "The women's Macroblade 90 pairs the fast 90mm setup with a cuff and liner shaped for a woman's foot and leg. The result is a secure, pressure-free fit that stays comfortable through long, fast fitness sessions — no compromise on speed.",
    tech: [
      { title: "Women's-Specific Fit", desc: "Cuff shape and liner volume tuned for a woman's foot and lower leg." },
      { title: "90mm / 84A Wheels", desc: "High-speed roll with a long, smooth glide." },
      { title: "Longer Aluminium Frame", desc: "Added wheelbase for stability at pace." },
      { title: "SG9 Bearings", desc: "Smooth, durable performance mile after mile." },
    ],
    target: "Women skaters at an intermediate level who want a fast, comfortable fitness skate built around their fit.",
    specs: { Wheels: "90mm / 84A", Bearings: "SG9", Frame: "Extruded aluminium", Liner: "Women's comfort", Closure: "Lace + strap + buckle", Sizes: "UK 3.5 – 8" },
  },
  {
    id: "mb84-boa", name: "Macroblade 84 BOA", color: "Black / Blue", price: 699,
    img: "assets/products/p5.webp", accent: "var(--blue-500)", badge: "BOA Dial", category: "Fitness Skate",
    tagline: "Micro-adjust your fit with a twist.",
    description: "The Macroblade 84 BOA swaps fiddly laces for the BOA Fit System — a dial that tightens the whole skate evenly with a twist, and pops off in a second. Get a precise, even hold that you can fine-tune mid-skate, on top of the comfortable, fast 84mm platform.",
    tech: [
      { title: "BOA Fit System", desc: "Dial-in an even, precise fit in seconds — adjust on the move, release instantly." },
      { title: "84mm / 84A Wheels", desc: "Fast yet controllable — ideal for fitness and city skating." },
      { title: "Extruded Aluminium Frame", desc: "Light, stiff and responsive underfoot." },
      { title: "SG9 Bearings", desc: "Consistent, smooth roll with low maintenance." },
    ],
    target: "Skaters who want quick, precise, on-the-fly fit adjustment without dealing with laces.",
    specs: { Wheels: "84mm / 84A", Bearings: "SG9", Frame: "Extruded aluminium", Liner: "Comfort padded", Closure: "BOA dial + strap", Sizes: "UK 4 – 12" },
  },
  {
    id: "mb90-boa", name: "Macroblade 90 BOA", color: "Grey / Red", price: 899,
    img: "assets/products/p6.webp", accent: "var(--yellow-500)", badge: "BOA Dial", category: "Performance Skate",
    tagline: "Top-of-the-line speed with dial-in precision.",
    description: "The flagship of the line. The Macroblade 90 BOA combines the fast 90mm performance platform with the BOA Fit System for the most precise, secure hold we offer. Longer glide, higher speed, and a fit you can perfect with a twist — the complete fitness performance package.",
    tech: [
      { title: "BOA Fit System", desc: "Precise, even micro-adjustment on demand for a locked-in performance fit." },
      { title: "90mm / 84A Wheels", desc: "Maximum roll speed and a long, efficient glide." },
      { title: "Longer Aluminium Frame", desc: "Extended wheelbase for stability and top-end speed." },
      { title: "SG9 Bearings", desc: "Fast, free-rolling and built to last." },
    ],
    target: "Committed intermediate-to-advanced skaters who want the fastest, most precise-fitting skate in the range.",
    specs: { Wheels: "90mm / 84A", Bearings: "SG9", Frame: "Extruded aluminium", Liner: "Performance padded", Closure: "BOA dial + strap", Sizes: "UK 4 – 12" },
  },
];
